name: Build LaTeX Report

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      report_name:
        description: "Name of the report PDF file"
        required: false

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize report name
        run: |
          if [ -n "${{ inputs.report_name }}" ]; then
            echo "SHORT_SHA=${{ inputs.report_name }}" >> $GITHUB_ENV
          else
            echo "SHORT_SHA=report-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Compile report
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true
          texlive_version: latest
          os: debian

      - name: Rename PDF
        run: |
          mv src/main.pdf "${SHORT_SHA}.pdf"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-year-report
          path: "${SHORT_SHA}.pdf"
